### ISSUE TITLE
Effects not working after FFXIV update.

### ISSUE THREAD

**Issue by babydoll** [wolfcomp/AuroraFFXIVPlugin#1]
See title, character is always InCombat according to the plugin in patch 5.3.

Everything else works as far as I can tell

**Comment by wolfcomp** [comment]
Remove the actions.json, signatures-x64-json, statuses.json, structures-x64.json, zones.json in the exe path of Aurora and it will fix it self

**Comment by babydoll** [comment]
Yep, thank you!
